POST http://localhost:3333/videos
Content-Type: application/json

{
    "title" : "video 1",
    "description": "Descrição",
    "duration": 129
}
###
GET http://localhost:3333/videos
###

PUT http://localhost:3333/videos/7139836a-dd19-4bdc-9ea0-5e4f49dbe879
Content-Type: application/json

{
    "title" : "video 121",
    "description": "Descrição",
    "duration": 129
}
###
DELETE  http://localhost:3333/videos/7139836a-dd19-4bdc-9ea0-5e4f49dbe879