name: CI/CD

on:
  pull_request:
    paths:
      - "**/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy pull request template
        run: |
          mkdir -p $GITHUB_WORKSPACE/.github
          cp .github/pull_request_template.md $GITHUB_WORKSPACE/.github/pull_request_template.md
